title: Eugen Dizer
description: Physics student at the University of Heidelberg. Passionate about science, productivity and making the world a better place.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-seo-tag